### ISSUE TITLE
interwencja

### ISSUE THREAD

**Issue by ag1zywert** [miriamkaminska/papa_swiecie#2]
Kochana _Miriam_ co to za samobójcza nazwa repo?
Mam nadzieję, że nie chcesz powiedzieć papa światu naprawdę, bo inaczaej **interwencja**
serdecznie pozdrowienia 
xoxo

**Comment by miriamkaminska** [comment]
Pozdrawiam Cię z zajęć. Pan Krzysztof również! Ubaw po pachy z twojego komentarza.

**Comment by ag1zywert** [comment]
Wiem, bo jestem takim _kawalarzem_ jak mało kto na tych studiach oraz planecie
Cieszę się, że mam wreszcie jakieś koleżanki na githubie i to _**jakie**_

**Comment by miriamkaminska** [comment]
love you
